version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER:  $DB_USER
      POSTGRES_DB: $DB_DATABASE
    network_mode: host
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    # create go and remix config
volumes:
  postgres_data: